<<<<<<< HEAD
var myFullName;
console.log(myFullName);
var myFullName="Sarika Pathare";
console.log(myFullName);
var myFullName="Sarika Vishnu Pathare";
console.log(myFullName);
var myLove="I love only js";
console.log(myLove);
var firstName="Sarika";
var lastName="Pathare";
var age="32";
var address="new mumbai";
var pinCode="410209";
var gender="female";
var isMarried="yes";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(address);
console.log(pinCode);
console.log(gender);
=======
var myFullName;
console.log(myFullName);
var myFullName="Sarika Pathare";
console.log(myFullName);
var myFullName="Sarika Vishnu Pathare";
console.log(myFullName);
var myLove="I love only js";
console.log(myLove);
var firstName="Sarika";
var lastName="Pathare";
var age="32";
var address="new mumbai";
var pinCode="410209";
var gender="female";
var isMarried="yes";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(address);
console.log(pinCode);
console.log(gender);
>>>>>>> 2c6f7fd26e60f7f9ffac8a56b26ae43100b76ec9
console.log(isMarried);